#install packages
install.packages("readxl")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("randomForest")
install.packages("caret")

library(readxl)
library(rpart)
library(rpart.plot)
library(randomForest)
library(caret)

#loading dataset
Assignment_df <- read_excel("Assignment section 3 data set.xlsx")
dim(Assignment_df)
head(Assignment_df, 3) #looking at first three rows 
table(Assignment_df$set)    #training 427 and test 142 
table(Assignment_df$diagnosis)


#spliting dataset using given column 
train <- Assignment_df[Assignment_df$set == "train", ]
test  <- Assignment_df[Assignment_df$set == "test", ]

#removing ID and set columns as it does not give biological meaning #*AI generated code to remove non relevant 
train <- train[ , !(names(train) %in% c("id", "set"))]
test  <- test[ , !(names(test) %in% c("id", "set"))]

dim(train)  
dim(test) 

#converting diagnosis as a factor as it is categorical
train$diagnosis <- as.factor(train$diagnosis)
test$diagnosis  <- as.factor(test$diagnosis)

#confirming factor for diagnosis
class(train$diagnosis)
levels(train$diagnosis)

#q1 building tree
set.seed(67)
tree_model <- rpart(diagnosis ~ ., #predicting diagnosis from all other columns
                    data  = train, #on train data
                    method = "class") #classify it as B/M

printcp(tree_model)
#root node error is 0.372 which means 37% is malignant
#as splits increases the error drops, final split is 6.9% error

#tree diagram
rpart.plot(tree_model, 
           type  = 4, 
           extra = 104,
           main  = "Decision Tree - Breast Cancer Diagnosis") #green is malignant and blue is benign

#on test data
pred_tree <- predict(tree_model, newdata = test, type = "class")

#confusion matrix
confusionMatrix(pred_tree, test$diagnosis, positive = "M") #predicted 79 benign and 48 as malignant correct
#5 predicted 5 as benign but was malignant and predicted 10 mal but was benign

#q2
set.seed(67)  # for reproducibility
rf_model <- randomForest(diagnosis ~ ., 
                         data  = train, 
                         ntree = 500)


#comparison with 18 trees
rf_model_cp <- randomForest(diagnosis ~ ., 
                         data  = train, 
                         ntree = 18)

print(rf_model) #oob of 3.5% good validation on bootstrap samples
print(rf_model_cp) #error is slightly increasing with low number of trees

pred_rf <- predict(rf_model, newdata = test)
confusionMatrix(pred_rf, test$diagnosis, positive = "M") #83 classified benign correctly predicted 47 mal correct
##6 as m but was B and 6 as b but was m #higher accuracy in Forrest 

#q3
#determining important feature 
tree_model$variable.importance #in tree
rf_model$importance #random Forrest

#bar plot #tree #codes to create bar plots were generated by AI
barplot(sort(tree_model$variable.importance, decreasing = FALSE),
        horiz  = TRUE,
        las    = 1,
        main   = "Decision Tree",
        xlab   = "Importance Score",
        col    = "steelblue",
        cex.names = 0.7)

rf_imp <- importance(rf_model, type = 2)
rf_vec <- rf_imp[, "MeanDecreaseGini"]  

barplot(sort(rf_vec, decreasing = FALSE),
        horiz = TRUE,
        las = 1,
        main = "Random Forest Variable Importance",
        xlab = "Mean Decrease Gini",
        col = "steelblue",
        cex.names = 0.7)


# Extract importance scores and sort them
rf_importance <- importance(rf_model)
rf_imp_sorted <- sort(rf_importance[,1], decreasing = FALSE)

# Take only top 15
rf_imp_top15 <- tail(rf_imp_sorted, 15)
rf_imp_top15

#decision tree graph 
par(mar = c(4, 12, 4, 2))
barplot(sort(tree_model$variable.importance, decreasing = FALSE),
        horiz  = TRUE,
        las    = 1,
        main   = "Decision Tree - Variable Importance",
        xlab   = "Importance Score",
        col    = "steelblue",
        cex.names = 0.7)

# Plot as horizontal bar chart
par(mar = c(4, 12, 4, 2))  # wide left margin for labels
barplot(rf_imp_top15,
        horiz  = TRUE,
        las    = 1,
        main   = "Random Forest - Top 15 Variable Importance",
        xlab   = "Mean Decrease Gini",
        col    = "darkgreen",
        cex.names = 0.8)

